### ISSUE TITLE
Improve diagnostic for incorrectly specified struct literals in the new parser

### ISSUE THREAD

**Issue by peterhuene** [stjude-rust-labs/wdl#78]
With gauntlet switched over to the new parser, it records this diagnostic:

```toml
[[diagnostics]]
document = "aws-samples/amazon-omics-tutorials:/example-workflows/gatk-best-practices/workflows/somatic-snps-and-indels/mutec2.wdl"
message = "mutec2.wdl:112:40: error: expected input section, output section, runtime section, metadata section, parameter metadata section, conditional statement, scatter statement, task call statement, or private declaration, but found `{`"
```

The source in question is:

```wdl
Runtime standard_runtime = Runtime {"gatk_docker": gatk_docker,
                                        "cpu": small_task_cpu,
                                        "machine_mem": small_task_mem * 1024,
                                        "command_mem": (small_task_mem * 1024) - 512}
```

Unfortunately, that's not legal syntax for a struct literal as the member names cannot be quoted.

What the new parser implementation is doing is attempting to recover after what is a valid (syntatically-speaking) expression:

```wdl
Runtime standard_runtime = Runtime
```

This is a private declaration with type `Runtime` (a type name reference) with name `standard_runtime` with expression `Runtime` (a name reference). If we were to evaluate that, it would be an error (i.e. `Runtime` names a type not a value).

So the next thing to parse is `{`, but the parser expects a workflow item, hence the confusing error.

I suggest we improve this during the disambiguation the takes place between a struct literal and a name reference.

When we `peek3` and we match `{` -> ? -> `:` where ? signifies something other than an identifier, we add a single diagnostic to report that a struct literal must use identifiers for member names and recover at the next `}`.
